# 1. ndArray

### (1) ndArray 생성

- 형식 : numpy.array() 함수에 객체를 인자로 추가하여 생성한다.
- 객체로 파이썬의 리스트를 생성하여 입력하여 자동으로 변환된다.

In [12]:
import numpy as np

# 1차원 배열 생성
# 리스트를 ndarray로 변환하여 생성
list1 = [1, 2, 3]
array1 = np.array(list1)
print(type(list1), type(array1))

array2 = np.array([1, 2, 3])
print(type(array2))

<class 'list'> <class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
array2 = np.array([1, 2, 3])
print(type(array2))

<class 'numpy.ndarray'>


In [14]:
# 튜플을 ndarray로 변환하여 생성
tuple1 = (1, 2, 3)
tarray1 = np.array(tuple1)
print(type(tarray1))
print(tarray1)

<class 'numpy.ndarray'>
[1 2 3]


In [15]:
# 세트를 ndarray로 변환하여 생성
set1 = {1, 2, 3}
sarray1 = np.array(list(set1))
print(type(sarray1))
print(sarray1)

<class 'numpy.ndarray'>
[1 2 3]


In [17]:
# 2차원 배열 생성
list2 = [[1,2],[3,4]]
array2 = np.array(list2) # 중첩 리스트 사용
print(type(array2))
print(array2)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]]


In [18]:
# 3차원 배열 생성
list3 = [[[1,2]],[[3,4]]]
array3 = np.array(list3) # 중첩 리스트 사용
print(type(array3))
print(array3)

<class 'numpy.ndarray'>
[[[1 2]]

 [[3 4]]]


### (2) shape와 ndim 
- shape : 배열의 모양(형태)
- ndim : 배열의 차원

In [20]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1], [2], [3]])
array3 = np.array([[[1]], [[2]], [[3]]])

In [24]:
print(f"1차원 : {array1.shape}")
print(f"2차원 : {array2.shape}")
print(f"3차원 : {array3.shape}")

1차원 : (3,)
2차원 : (3, 1)
3차원 : (3, 1, 1)


In [29]:
print(f"1차원 : {array1.ndim}")
print(f"2차원 : {array2.ndim}")
print(f"3차원 : {array3.ndim}")

1차원 : 1
2차원 : 2
3차원 : 3


### (3) dtype 
- 저장된 데이터 타입 확인
- 모든 데이터 타입이 동일 해야함

In [35]:
# 정수 배열
arr_int = np.array([1, 2, 3])
print(type(arr_int))
print(arr_int.dtype) # int64

<class 'numpy.ndarray'>
int64
