# 1. ndArray

### (1) ndArray 생성

- 형식 : numpy.array() 함수에 객체를 인자로 추가하여 생성한다.
- 객체로 파이썬의 리스트를 생성하여 입력하여 자동으로 변환된다.

In [12]:
import numpy as np

# 1차원 배열 생성
# 리스트를 ndarray로 변환하여 생성
list1 = [1, 2, 3]
array1 = np.array(list1)
print(type(list1), type(array1))

array2 = np.array([1, 2, 3])
print(type(array2))

<class 'list'> <class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [11]:
array2 = np.array([1, 2, 3])
print(type(array2))

<class 'numpy.ndarray'>


In [14]:
# 튜플을 ndarray로 변환하여 생성
tuple1 = (1, 2, 3)
tarray1 = np.array(tuple1)
print(type(tarray1))
print(tarray1)

<class 'numpy.ndarray'>
[1 2 3]


In [15]:
# 세트를 ndarray로 변환하여 생성
set1 = {1, 2, 3}
sarray1 = np.array(list(set1))
print(type(sarray1))
print(sarray1)

<class 'numpy.ndarray'>
[1 2 3]


In [17]:
# 2차원 배열 생성
list2 = [[1,2],[3,4]]
array2 = np.array(list2) # 중첩 리스트 사용
print(type(array2))
print(array2)

<class 'numpy.ndarray'>
[[1 2]
 [3 4]]


In [18]:
# 3차원 배열 생성
list3 = [[[1,2]],[[3,4]]]
array3 = np.array(list3) # 중첩 리스트 사용
print(type(array3))
print(array3)

<class 'numpy.ndarray'>
[[[1 2]]

 [[3 4]]]


### (2) shape와 ndim 
- shape : 배열의 모양(형태)
- ndim : 배열의 차원

In [20]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1], [2], [3]])
array3 = np.array([[[1]], [[2]], [[3]]])

In [24]:
print(f"1차원 : {array1.shape}")
print(f"2차원 : {array2.shape}")
print(f"3차원 : {array3.shape}")

1차원 : (3,)
2차원 : (3, 1)
3차원 : (3, 1, 1)


In [29]:
print(f"1차원 : {array1.ndim}")
print(f"2차원 : {array2.ndim}")
print(f"3차원 : {array3.ndim}")

1차원 : 1
2차원 : 2
3차원 : 3


### (3) dtype 
- 저장된 데이터 타입 확인
- 모든 데이터 타입이 동일 해야함

In [35]:
# 정수 배열
arr_int = np.array([1, 2, 3])
print(type(arr_int))
print(arr_int.dtype) # int64

<class 'numpy.ndarray'>
int64


In [37]:
# 실수 배열
arr_float = np.array([1.23, 2.34, 3.0])
print(type(arr_float))
print(arr_float.dtype) # float64

<class 'numpy.ndarray'>
float64


In [38]:
# 문자열 배열
arr_str = np.array(['a','b','c'])
print(type(arr_str))
print(arr_str.dtype) # <U1

<class 'numpy.ndarray'>
<U1


### (4) 자동 형변환

- 여러 타입이 저장되는 경우 가장 큰 타입으로 자동 변환

In [40]:
# 정수 + 문자열 => 문자열 타입 저장
arr = np.array([1, 2, 'abc'])
arr

array(['1', '2', 'abc'], dtype='<U21')

In [43]:
# 정수 + 실수 => 실수 타입으로 저장
arr = np.array([1, 2, 3.123])
arr

array([1.   , 2.   , 3.123])

In [44]:
# 실수 + 문자열 => 문자열 타입으로 저장 : 정수 < 실수 < 문자열
arr = np.array([1.0, 2.12, 'test'])
arr

array(['1.0', '2.12', 'test'], dtype='<U32')

### (5) 데이터 타입 변환 - astype()
- 데이터 타입을 명시적으로 변환
- 자주 사용하는 dtype 종류
  |dtype|설명|메모리|
  |------|----|-----|
  |int32|32비트 정수|4바이트|
  |int64|64비트 정수(기본값)|8바이트|
  |float32|32비트 실수|4바이트|
  |float64|64비트 실수(기본값)|8바이트|
  |bool|불린 (True/False)|1바이트|
  |<U숫자|유니코드 문자열|가변|

In [46]:
arr_int = np.array([1, 2, 3])
arr_int.dtype

dtype('int64')

In [47]:
# arr_int 배열을 float64 타입의 배열로 변환
arr_float = arr_int.astype('float64')
arr_float

array([1., 2., 3.])

In [48]:
# arr_float 배열을 int32 타입의 배열로 변환
arr_int32 = arr_float.astype('int32')
arr_int32

array([1, 2, 3], dtype=int32)

In [51]:
# arr_int32 배열을 문자열 배열로 변환
arr_str = arr_int32.astype('<U1')
arr_str

array(['1', '2', '3'], dtype='<U1')

### (6) 데이터 생성 함수 - arange()
- 파이썬의 range() 함수와 유사하며, 연속된 데이터를 생성
- np.arange(start, end, step)

In [53]:
# 0~9까지 데이터 생성
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
# 0~1까지 0.2 만큼씩 증가
arr = np.arange(0, 1, 0.2)
arr

array([0. , 0.2, 0.4, 0.6, 0.8])

### (7) np.zeros(), np.ones()
- np.zeros() : 모든 데이터가 0인 배열
- np.ones() : 모든 데이터가 1인 배열

In [63]:
# 3행의 1차원 배열 생성 후, 모든 데이터를 0으로 초기화
arr_zeros = np.zeros((3,), dtype='int64')
arr_zeros

array([0, 0, 0])

In [64]:
# 모든 데이터를 0으로 갖는 3행 4열의 2차원 배열 생성
arr_zeros = np.zeros((3, 4), dtype='int64')
arr_zeros

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])