# 인덱싱(indexing)

- ndarray에서 데이터를 검색하는 방법
- 인덱싱 방법
|종류|방법 | 특징|
|-----|-----|-----|
|단일값 인덱싱|arr[2]| 특정위치 단일값 출력|
|슬라이싱|arr[1:4]| 연속된 범위|
|팬시인덱싱|arr[[0, 2, 4]]|불연속 위치 다중값 출력|
|불린인덱싱|arr[arr > 5]| 조건에 맞는 값 출력|

### (1) 단일값 인덱싱

In [1]:
import numpy as np

In [5]:
#1~9까지 ndarray 데이터 생성
arr = np.arange(1, 10)
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# 2번지의 데이터 출력
print(type(arr))
print(type(arr[2]))

print(arr.dtype)
print(arr[2].dtype)

print(arr.shape)
print(arr[2].shape)

<class 'numpy.ndarray'>
<class 'numpy.int64'>
int64
int64
(9,)
()


In [17]:
# 인덱스별 단일값 출력
print(arr)
print(arr[0])
print(arr[2])
print(arr[5])
print(arr[-1])
print(arr[-2])

[1 2 3 4 5 6 7 8 9]
1
3
6
9
8


### (2) 단일값 인덱싱을 통한 데이터 변경

In [22]:
arr[0] = 100
print(arr)
arr[-1] = 900
print(arr)

[100   2   3   4   5   6   7   8 900]
[100   2   3   4   5   6   7   8 900]
