# 배열 연산
- 배열의 shape이 같으면 데이터별로 연산이 진행됨

In [3]:
import numpy as np

In [12]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1.shape, arr2.shape)
print(arr1, arr2)

(3,) (3,)
[1 2 3] [4 5 6]


In [13]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


In [ ]:
# shape이 다른 경우 ValueError 발생 💥
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([4, 5, 6])
print(arr1.shape, arr2.shape)
print(arr1 + arr2)

- 스칼라(단일 숫자)와 연산

In [18]:
print(arr1 + 10)
print(arr1 - 1)
print(arr1 * 3)
print(arr1 / 2)

[11 12 13 14]
[0 1 2 3]
[ 3  6  9 12]
[0.5 1.  1.5 2. ]


- 2차원 배열 연산

In [25]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1.shape, arr2.shape)

(2, 2) (2, 2)


In [26]:
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
